# Generated by Django 4.2.16 on 2024-09-28 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epi_shops', '0004_alter_cargos_options_alter_carrinhos_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargos',
            options={},
        ),
        migrations.AlterModelOptions(
            name='carrinhos',
            options={},
        ),
        migrations.AlterModelOptions(
            name='categorias',
            options={},
        ),
        migrations.AlterModelOptions(
            name='clientes',
            options={},
        ),
        migrations.AlterModelOptions(
            name='emprestimos',
            options={},
        ),
        migrations.AlterModelOptions(
            name='epis',
            options={},
        ),
        migrations.AlterModelOptions(
            name='funcionarios',
            options={},
        ),
        migrations.AlterModelOptions(
            name='historico',
            options={},
        ),
        migrations.AlterModelOptions(
            name='manutencoes',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pagamentos',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={},
        ),
        migrations.AlterModelManagers(
            name='usuarios',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='tipo_usuario',
            field=models.CharField(choices=[('Cliente', 'Cliente'), ('Funcionario', 'Funcionario'), ('Gerente', 'Gerente')], max_length=12),
        ),
    ]
