# Generated by Django 4.2.16 on 2024-09-28 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epi_shops', '0006_alter_cargos_options_alter_carrinhos_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargos',
            options={'verbose_name': 'Cargo', 'verbose_name_plural': 'Cargos'},
        ),
        migrations.AlterModelOptions(
            name='carrinhos',
            options={'verbose_name': 'Carrinho', 'verbose_name_plural': 'Carrinhos'},
        ),
        migrations.AlterModelOptions(
            name='categorias',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='clientes',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='emprestimos',
            options={'verbose_name': 'Emprestimo', 'verbose_name_plural': 'Emprestimos'},
        ),
        migrations.AlterModelOptions(
            name='epis',
            options={'verbose_name': 'Epis', 'verbose_name_plural': 'Epis'},
        ),
        migrations.AlterModelOptions(
            name='funcionarios',
            options={'verbose_name': 'Funcionario', 'verbose_name_plural': 'Funcionarios'},
        ),
        migrations.AlterModelOptions(
            name='historico',
            options={'verbose_name': 'Historico', 'verbose_name_plural': 'Historicos'},
        ),
        migrations.AlterModelOptions(
            name='manutencoes',
            options={'verbose_name': 'Manutenção', 'verbose_name_plural': 'Manutenções'},
        ),
        migrations.AlterModelOptions(
            name='pagamentos',
            options={'verbose_name': 'Pagaamento', 'verbose_name_plural': 'Pagamentos'},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
