# Generated by Django 4.2.16 on 2024-09-28 19:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('epi_shops', '0007_alter_cargos_options_alter_carrinhos_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='epis',
            options={'verbose_name': 'Epi', 'verbose_name_plural': 'Epis'},
        ),
        migrations.AlterModelOptions(
            name='pagamentos',
            options={'verbose_name': 'Pagamento', 'verbose_name_plural': 'Pagamentos'},
        ),
        migrations.RenameField(
            model_name='emprestimos',
            old_name='emprestimo',
            new_name='data_emprestimo',
        ),
        migrations.RemoveField(
            model_name='epis',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='funcionarios',
            name='admissao',
        ),
        migrations.AddField(
            model_name='epis',
            name='descricao',
            field=models.TextField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carrinhos',
            name='clientes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epi_shops_carrinhos', to='epi_shops.clientes'),
        ),
        migrations.AlterField(
            model_name='carrinhos',
            name='epis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epi_shops_carrinhos', to='epi_shops.epis'),
        ),
        migrations.AlterField(
            model_name='carrinhos',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cnpj',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='usuarios',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='epi_shops_cliente', to='epi_shops.usuarios'),
        ),
        migrations.AlterField(
            model_name='emprestimos',
            name='clientes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epi_shops_emprestimos', to='epi_shops.clientes'),
        ),
        migrations.AlterField(
            model_name='emprestimos',
            name='devolucao_efetiva',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='epis',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epi_shops_epis', to='epi_shops.categorias'),
        ),
        migrations.AlterField(
            model_name='epis',
            name='disponibilidade',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='epis',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='cargos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epi_shops_funcionarios', to='epi_shops.cargos'),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='usuarios',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='epi_shops_funcionario', to='epi_shops.usuarios'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='clientes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epi_shops_historico_cliente', to='epi_shops.clientes'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='historico',
            name='epis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epi_shops_historico_epi', to='epi_shops.epis'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='pagamentos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='epi_shops_historico_pagamento', to='epi_shops.pagamentos'),
        ),
        migrations.AlterField(
            model_name='manutencoes',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manutencoes',
            name='epis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epi_shops_manutencoes', to='epi_shops.epis'),
        ),
        migrations.AlterField(
            model_name='pagamentos',
            name='clientes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epi_shops_pagamentos', to='epi_shops.clientes'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='epi_shops_usuarios_groups', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='epi_shops_usuarios_user_permissions', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
