# Generated by Django 4.2.16 on 2024-09-28 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epi_shops', '0007_alter_cargos_options_alter_carrinhos_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargos',
            options={'verbose_name_plural': 'Cargos'},
        ),
        migrations.AlterModelOptions(
            name='carrinhos',
            options={'verbose_name_plural': 'Carrinhos'},
        ),
        migrations.AlterModelOptions(
            name='categorias',
            options={'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='clientes',
            options={'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='emprestimos',
            options={'verbose_name_plural': 'Emprestimos'},
        ),
        migrations.AlterModelOptions(
            name='epis',
            options={'verbose_name_plural': 'Epis'},
        ),
        migrations.AlterModelOptions(
            name='funcionarios',
            options={'verbose_name_plural': 'Funcionários'},
        ),
        migrations.AlterModelOptions(
            name='historico',
            options={'verbose_name_plural': 'Historico'},
        ),
        migrations.AlterModelOptions(
            name='manutencoes',
            options={'verbose_name_plural': 'Manutenções'},
        ),
        migrations.AlterModelOptions(
            name='pagamentos',
            options={'verbose_name_plural': 'Pagamentos'},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelManagers(
            name='usuarios',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='user_permissions',
        ),
    ]
