# Generated by Django 5.1.1 on 2024-10-02 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epi_shops', '0008_alter_cargos_options_alter_carrinhos_options_and_more'),
        ('epi_shops', '0008_alter_epis_options_alter_pagamentos_options_and_more'),
    ]

    operations = [
    ]
